# Generated by Django 2.0.3 on 2018-08-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户名', 'verbose_name_plural': '用户名'},
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
