# Generated by Django 2.0.3 on 2018-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180816_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uphone',
            field=models.CharField(max_length=11, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upwd',
            field=models.CharField(max_length=30, verbose_name='密码'),
        ),
    ]
