# Generated by Django 2.0.3 on 2018-08-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180816_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
