# Generated by Django 2.0.3 on 2018-08-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_position'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='position',
            table='position',
        ),
    ]
