# Generated by Django 2.0.3 on 2018-08-23 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180823_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=30, verbose_name='地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户位置',
                'verbose_name_plural': '用户位置',
                'db_table': 'adress',
            },
        ),
        migrations.RemoveField(
            model_name='position',
            name='user',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
